// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3316mmzeuoqXCo0zh1sHlaaKLsPRAkOA',
    appId: '1:430403147975:web:5fcc92e9c893cbbc4a06e2',
    messagingSenderId: '430403147975',
    projectId: 'stocksense-bitnbuild',
    authDomain: 'stocksense-bitnbuild.firebaseapp.com',
    storageBucket: 'stocksense-bitnbuild.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWhKXb_ZIpHMgJau1jRaErd0W-WM8qot0',
    appId: '1:430403147975:android:7868e225a541c4c14a06e2',
    messagingSenderId: '430403147975',
    projectId: 'stocksense-bitnbuild',
    storageBucket: 'stocksense-bitnbuild.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCs6I0fui8qABvR2MFUmrL9Ps9d-67G5k',
    appId: '1:430403147975:ios:168c6b29f14ede404a06e2',
    messagingSenderId: '430403147975',
    projectId: 'stocksense-bitnbuild',
    storageBucket: 'stocksense-bitnbuild.appspot.com',
    iosBundleId: 'com.example.stocksenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCs6I0fui8qABvR2MFUmrL9Ps9d-67G5k',
    appId: '1:430403147975:ios:851e5d3a2dab90524a06e2',
    messagingSenderId: '430403147975',
    projectId: 'stocksense-bitnbuild',
    storageBucket: 'stocksense-bitnbuild.appspot.com',
    iosBundleId: 'com.example.stocksenseApp.RunnerTests',
  );
}
